[tool.jhonmicro]
name = "jhonmicro"
version = "0.1.0"
description = "Official Discord bot for Micro Jam"
readme = "README.md"
requires-python = ">=3.8"

# Dependencies should be specified directly under the tool section
dependencies = [
    "discord>=2.3.2",
    "discord-py[voice]>=2.5.2",
    "python-dotenv>=0.9.9",  # Corrected the package name to 'python-dotenv'
    "logging>=0.4.9.6",
    "vacefron-py>=2.0.3",
]
